### ISSUE TITLE
Nested templates

### ISSUE THREAD

**Issue by Loskir** [telegraf/telegraf-i18n#39]
Add the `t` function to `templateData` so that we can use `t` inside the template itself

For example:
```yaml
greeting: hello!
main: i like trains.
end: bye!

text: |-
  ${t('greeting')}

  ${t('main')}

  ${t('end')}
```
